<?php
/**
 * @file
 * yamaps_modal.module
 */

/**
 * Implements hook_field_formatter_info().
 */
function yamaps_modal_field_formatter_info() {
  return array(
    'field_yamaps_formatter_modal_window' => array(
      'label' => t('Modal window'),
      'field types' => array('field_yamaps'),
      'settings' => array(
        'original_field' => array(
          'type' => 'field_yamaps_formatter_static',
          // Possible variants static_image, button.
          'field_settings' => array(),
        ),
        'modal_window_settings' => array(
          'type' => 'field_yamaps_formatter_dynamic',
          // Possible variants static_image, dynamic_cart.
          'field_settings' => array(),
        ),
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function yamaps_modal_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();

  switch ($display['type']) {
    case 'field_yamaps_formatter_modal_window':
      $element['original_field_type'] = array(
        '#title' => t('Original field type'),
        '#type' => 'radios',
        '#default_value' => $settings['s_height'],
        '#options' => array(
          'button' => t('Open button'),
          'field_yamaps_formatter_static' => t('Static image'),
        ),
        '#required' => TRUE,

      );

      $element['modal_window_field_type'] = array(
        '#title' => t('Modal window field type'),
        '#type' => 'radios',
        '#default_value' => $settings['s_height'],
        '#options' => array(
          'field_yamaps_formatter_dynamic' => t('Dynamic image'),
          'field_yamaps_formatter_static' => t('Static image'),

        ),
        '#required' => TRUE,

      );
      break;

  }
  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function yamaps_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = array();

  switch ($display['type']) {
    case 'field_yamaps_formatter_modal_window':
      $summary[] = t('Original field settings: @field_settings', array('@field_settings' => ''));
      $summary[] = t('Modal window settings: @field_settings', array('@field_settings' => ''));
      break;
  }

  return implode('<br />', $summary);
}

/**
 * Implements hook_field_formatter_view().
 */
function yamaps_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];
  $entity_info = entity_get_info($entity_type);
  $entity_id = uniqid();

  if (isset($entity_info['entity keys']['id']) && isset($entity->{$entity_info['entity keys']['id']})) {
    $entity_id = $entity->{$entity_info['entity keys']['id']};
  }

  switch ($display['type']) {
    case 'field_yamaps_formatter_modal_window':
      //@todo create logic for combined type.
      break;
  }
  return $element;
}



/**
 * Get list of modal libraries.
 *
 * @return array
 */
function yamaps_modal_get_modals_list() {
  $list = array();

  $list['standalone'] = t('Standalone library');

  if (libraries_detect('colorbox')) {
    $list['colorbox'] = t('Colorbox');
  }

  if (libraries_detect('fancybox')) {
    $list['fancybox'] = t('Fancybox');
  }
  if (libraries_detect('shadowbox')) {
    $list['shadowbox'] = t('Shadowbox');
  }
  return $list;
}

function yamaps_modal_show_map($settings) {

}

function theme_yandex_modal_fancybox() {
  $drupal_id = drupal_html_id(implode('-', arary('fancybox', 'modal')));
  $output = l('text', '#' . $drupal_id, array('attributes' => array('class' => array('yandex-fancybox'))));

  $output .= '<div ' . drupal_attributes(array('id' => $drupal_id, 'class' => array(), 'style' => '')) . '>' . '</div>';
  return $output;
}
