<?php
/**
 * @file
 * Adds a formatter for view and create view button.
 */

/**
 * Implements hook_views_api().
 */
function yamaps_views_views_api() {
  return array('api' => 3);
}

/**
 * Implements hook_theme().
 */
function yamaps_views_theme() {
  return array(
    'yandex_balloon_content' => array(
      'template' => 'yandex-balloon-content',
      'variables' => array(
        'view' => NULL,
        'rendered_fields' => NULL,
        'item' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_help().
 */
function yamaps_views_help($path, $arg) {
  switch ($path) {
    case 'admin/help#yamaps_views':
      return t('Check !link for tutorials and videos on how to use this module.',
        array('!link' => l('Yandex Maps page', 'admin/help/yamaps')));
  }
}
