<?php
/**
 * @file
 * Adds a formatter for view and create view button.
 */

/**
 * Implements hook_views_api().
 */
function yamaps_views_views_api() {
  return array('api' => 3);
}

/**
 * Implements hook_help().
 */
function yamaps_views_help($path, $arg) {
  switch ($path) {
    case 'admin/help#yamaps_views':
      return t('Check !link for tutorials and videos on how to use this module.',
        array('!link' => l(t('Yandex Maps page'), 'admin/help/yamaps')));
  }
}

/**
 * Implements hook_views_pre_render().
 *
 * @param $view
 */
function yamaps_views_views_pre_render(&$view) {
  foreach ($view->field as $field) {
    if (isset($field->field_info['type']) && $field->field_info['type'] == 'field_yamaps') {
      global $language;
      $api_url = url(YAMAPS_API_URL, array(
        'absolute' => TRUE,
        'query' => array(
          'load' => 'package.full',
          'lang' => YAMAPS_API_LANGUAGE,
          'wizard' => 'Drupal_yamaps_' . $language->language,
        )
      ));

      // Load 'Yandex.Maps' API in views admin UI to make sure that it is fully
      // loaded before calling it during views ajax operations.
      $page['content']['#attached']['js'][] = $api_url;
      break;
    }
  }
}
